file_settings:
  teacher_education_file: '../assets/staff/teacher-attainment/****-Teacher-Attainment.xlsx'
  sheet_name: 'Teacher Attainment'
  start_row: 8
  years: [2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025]
  sql_cache_dir: '../sql_cache'

column_mappings:
  district_id: 2
  total_teachers: 4
  bachelor_percent: 5
  masters_percent: 6
  beyond_masters_percent: 7 

# Settings for identifying and processing state-level data
state_data_settings:
  # The column index (0-based) where the state identifier text is expected to be found
  state_column_index: 3
  # The text string that identifies a row as containing state totals
  state_identifier_text: "State Total" 